# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b52638762de0513d38d4492ad17916724d1279b057e317b9d7e9d7c403d153430fac339297caa5794bbbc1f680efbba813e4b4ff8cd97cbc81cb6385366a184

test:
  secret_key_base: a2c711ff7eecd6f6923e56debadc6de6c5c57b92b647598076f2de728116d5321a22df1b0805947b906958cf75cacc8d641218fef6742608938455c8789d557e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
